# wallust v3.4
#
# You can copy this file to ~/.config/wallust/wallust.toml (keep in mind is a sample config)

# SIMPLE TUTORIAL, or `man wallust.5`:
# https://explosion-mental.codeberg.page/wallust/
#
# If comming from v2: https://explosion-mental.codeberg.page/wallust/v3.html#wallusttoml

# Global section - values below can be overwritten by command line flags

# How the image is parse, in order to get the colors:
# full - resized - wal - thumb - fastresize - kmeans
backend = "fastresize"

# What color space to use to produce and select the most prominent colors:
# lab - labmixed - lch - lchmixed
color_space = "lch"

# Use the most prominent colors in a way that makes sense, a scheme color palette:
# dark - dark16 - darkcomp - darkcomp16
# light - light16 - lightcomp - lightcomp16
# harddark - harddark16 - harddarkcomp - harddarkcomp16
# softdark - softdark16 - softdarkcomp - softdarkcomp16
# softlight - softlight16 - softlightcomp - softlightcomp16
palette = "dark"
pywal=true
# NOTE: prefer '' over "" for paths, avoids escaping.
# template: A RELATIVE path that points to `~/.config/wallust/template` (depends on platform)
# target: ABSOLUTE path in which to place a file with generated templated values.
# ยก If either one is a directory, then both SHOULD be one. !
[templates]
ghostty = { template = 'ghostty.mustache', target = '~/.config/ghostty/colors.conf' }
zsh = { template = 'zsh.mustache', target = '~/.cache/wallust/colors.zsh' }
hyprland = { template = "hyprland.mustache", target = "~/.config/hypr/colors.conf" }
waybar = { template = "waybar.css", target = "~/.config/waybar/colors.css" }
neopywal.template = "colors_neopywal.vim"
wlogout-style = { template = "wlogout-style.css", target = "~/.config/wlogout/wall-style.css" }
neopywal.target = "~/.cache/wallust/colors_neopywal.vim"
rofi.template = 'colors-rofi.rasi'
rofi.target = '~/.config/rofi/colors.rasi'
